#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PDIR="$DIR/.."

set -e

function run {
	exe=$1

	if [[ -z "$exe" ]]; then
		echo "In run: nothing to do"
		return 0
	fi

	pushd "$PDIR/src/$exe" > /dev/null
	echo "========================================= $exe" 
	if [[ -f "./run" ]]; then
		echo "==> Running run file"
		"./run" 
	elif [[ -f "./build/$exe" ]]; then
		echo "==> Running direct"
		"./build/$exe" 
	elif [[ -f "./build/program" ]]; then
		echo "==> Running ./build/program"
		"./build/program"
	else
		echo "==> Running from makefile"
		make run
	fi
	popd > /dev/null
	err=$?
	echo "Exit Code => $err"
	if [[ $err -gt 0 ]]; then 
		echo "ERROR"
		return 1
	fi
}

if [[ $# -gt 0 ]]; then
	while [[ $# -gt 0 ]]
	do
		run "$1"
		[[ $? -gt 0 ]] && echo "Error" && exit 1
		shift
	done
else
	for dir in $(ls -p $PDIR/src/ | grep /); do
		run "$dir"
	done
fi
